return {}
-- return {
--   {
--     "nvimtools/none-ls.nvim",
--     enabled = false,
--     opts = function()
--       local nls = require("null-ls")
--       return {
--         root_dir = require("null-ls.utils").root_pattern(".null-ls-root", ".neoconf.json", "Makefile", ".git"),
--         sources = {
--           nls.builtins.formatting.stylua,
--           nls.builtins.formatting.shfmt,
--           nls.builtins.diagnostics.golangci_lint,
--         },
--       }
--     end,
--   },
-- }
